apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: comment-microservice
spec:
  rules:
    - host: ae14e5677d7da450f9ae33784a66da5c-556940459.us-east-1.elb.amazonaws.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: comment-microservice
                port:
                  number: 80
