apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: comment-microservice
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: "/comments"
            backend:
              service:
                name: comment-microservice
                port:
                  number: 80
